
```{r}
#loading libraries
library(ggplot2)
library(tidyverse)
library(dplyr)
library(caret)
library(lattice)
```


```{r}

# loading dataset
data <- read.csv("G:/surya/4th year/7th sem/foundation of data analytics/r prjocet 1/EURUSD60.csv", header=T)
head(data)
#In the context of trading, the price at which a share is being purchased or sold in the stock market at a given point of time is known as its trade price.
```

```{r}
nrow(data)
colnames(data)
str(data)
```


```{r}
######################
#data visuvaliztion part
#####################

#from  the histogram we can clearly say the range of values are from 1.20... to 1.50...and also
# the no of times each value is repeted
hist(data$open, main = 'open trade visuvalization',
     xlab = 'close trade price', col='red')
hist(data$close, main = 'close trade visuvalization',
     xlab = 'close trade price', col='red')

```

```{r}

#density plots gives you the values ranged  in curve format
densityplot(~data$close, main="Density Plot",  xlab="Range of values")

```

```{r}

# plot helps you to know the fluctuation of values or the trade price or trade values
plot(data$open, xlab = 'index', ylab = 'close trade values', 
     main = 'close trade visuvalization', col = 'green')
plot(data$close, xlab = 'index', ylab = 'close trade values', 
     main = 'close trade visuvalization', col = 'green')
```

```{r}
#as box plot is not much more use full for project but hepls to see max range values held range
boxplot(data$open,
        main = "trade close vlaues visuvalization",
        xlab = " range",
        ylab = "index",
        col = "orange",
        border = "brown",
        horizontal = TRUE,
        notch = TRUE
)
boxplot(data$close,
        main = "trade close vlaues visuvalization",
        xlab = " range",
        ylab = "index",
        col = "orange",
        border = "brown",
        horizontal = TRUE,
        notch = TRUE
)

```

```{r}
plot(data$close,type= "h")
plot(data$open,type= "h")

```

```{r}
plot(data$open,data$close)
```

```{r}

ggplot(data  = data)  +geom_point(mapping  
=aes(x=open,y=close))+theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

ggplot(data  = data)  +geom_point(mapping  
=aes(x=high,y=low))+theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5))

```

```{r}
plot(data)
```

```{r}
########################
# implementation part
#########################
# convert date/time types
data$date <- strptime(data$date, format="%m/%d/%Y %H:%M")
data$date <- as.POSIXct(data$date)
```

```{r}


#define a shift function for future use
shift <- function(x, n){
  c(x[-(seq(n))], rep(NA, n))
}

# mark bullish candles
data$bull <- 1
data$bull <- ifelse(data$open > data$close, 0, data$bull)

```

```{r}

# count consecutive bullish ("1")/ bearish("0") candles
data$count <- 1
for (i in 2:nrow(data)){
  if(data[i,]$bull == data[i-1,]$bull) {
    data[i,]$count <- data[i-1,]$count+1
  }
}
# ------------------- 
head(data, 20)
# --------------
```

```{r}
##########################################################
#stock trend change 
##########################################################


# mark what the next candle was
data$nextcount <- shift(data$count, 1)
# ------------------- 
head(data, 20)
# -------------------
```

```{r}
# create a table that contains the number of events, for example, after 3 consecutive candles, 
# how many times did the trend continue vs how many times did the trend change

mytable <- table(data$count, data$nextcount)

# ------------------- table of the quantities of the events
mytable
# -------------------
#count-row,nextcount,column
```

```{r}

# calculate the probabilities of the events
percent.table <- prop.table(mytable, 1)

# ------------------- table of probabilities
print.table(local({percent.table[percent.table==0] <- NA; percent.table}))
# ------------------- 



```


```{r}
# Now lets see if this makes money
# After x consecutive candles, trade in the opposite direction

# save the open/close prices for trading
data$nextopen <- shift(data$open, 1)
data$nextclose <- shift(data$close, 1)

# ------------------- lets see what the data looks like
head(data, 20)
# -------------------
```

```{r}
# when count is 7, buy/sell the opposite way
# filter for 7 consecutive candles
trades <- subset(data, data$count >= 7)
head(trades)
```

```{r}
# mark which direction we need to trade
trades$direction <- 1
trades$direction <- ifelse(trades$bull == 1, -1, trades$direction)
head(trades$direction)
```

```{r}
# set 0 cost of trde for now

trades$cost <- 0.000

# calculate the profit and a running total
trades$profit <- trades$direction*(trades$nextclose - trades$nextopen) - trades$cost
head(trades$profit)
trades$balance <- cumsum(trades$profit)
head(trades$balance)
# ------------------- plot the results
plot(trades$balance)
# -------------------
```

```{r}
# change the trade cost and recalculate the profitability
trades$cost <- 0.0002
trades$profit <- trades$direction*(trades$nextclose - trades$nextopen) - trades$cost
head(trades$profit)
trades$balance <- cumsum(trades$profit)

# ------------------- plot the results
plot(trades$balance)
# -------------------
```

```{r}
######################################################
# classefing trading cyclicality
######################################################
# add a row number - why? so that we can smooth without taking into account a non-uniform time axis (weekends / holidays)
data$row <- seq(1, nrow(data), 1)
head(data$row,20)
```

```{r}
# smooth the price graph 
data$smoothed <- ksmooth(data$row, data$close, "normal", bandwidth = 20)$y
head(data$smoothed,30)
```

```{r}
# ------------------- this is what part of the data and curve looks like
plot(data[1:200,]$close)
lines(data[1:200,]$smoothed, col="red")
# -------------------
```

```{r}
# now find the peaks and troughs
peaks <- which(diff(diff(data$smoothed)>=0)<0)+1
troughs <- which(diff(diff(data$smoothed)>0)>0)+1
data$minmax <- 0
data$minmax <- ifelse(data$row %in% peaks, 1, data$minmax)
data$minmax <- ifelse(data$row %in% troughs, -1, data$minmax)

```

```{r}
# ------------------- and with the peaks and troughs we have identified
ggplot(data[1:200,], aes(row)) + 
  geom_point(aes(y = close, colour = "close"), size = 3) + 
  geom_line(aes(y = smoothed, colour = "smoothed"), size = 1.2) +
  geom_point(data = subset(data, data$minmax == 1 & data$row <= 200), 
             aes(y=smoothed), color="red", size = 4) +
  geom_point(data = subset(data, data$minmax == -1 & data$row <= 200), 
             aes(y=smoothed), color="green", size = 4) +
  theme_bw() +
  theme(legend.position="none") 
# -------------------
```



```{r}
# now we want to plot what the cyclicality looks like
# so we plot price difference vs time difference 
# lets create a temporary dataframe to see these values
tmp1 <- subset(data, data$minmax != 0)
head(tmp1)
```

```{r}
tmp1$pricediff <- c(NA, abs(diff(tmp1$smoothed)))
tmp1$candlediff <- c(NA, diff(tmp1$row))
head(tmp1$pricediff,40)
head(tmp1$candlediff,40)
```

```{r}
# ------------------- use this plot to decide how to trade this thing
# from this plot we can deduce what is / is not tradable
plot(tmp1$pricediff, tmp1$candlediff)
abline(v= 0.012, col="red")
abline(h= 35, col = "red")
# -------------------
```

```{r}
pricediff_perc <- ecdf(tmp1$pricediff)(0.012)
candlediff_perc <- ecdf(tmp1$candlediff)(35)
pricediff_perc
candlediff_perc
```

```{r}
# now we work out the value from the percentile
pricediff_value <- quantile(tmp1$pricediff, pricediff_perc, na.rm=T)
candlediff_value <- quantile(tmp1$candlediff, candlediff_perc, na.rm=T)

pricediff_value
candlediff_value
```

```{r}
# ---------------- for interest sake, lets see what these cut-offs look like on a histogram
hist(tmp1$pricediff)
abline(v= pricediff_value, col="red")

hist(tmp1$candlediff)
abline(v= candlediff_value, col="red")
# -------------------
```

```{r}
# based on the visual analysis we made, filter for the trading opportunities
tmp2 <- subset(tmp1, tmp1$pricediff >= pricediff_value & tmp1$candlediff <= candlediff_value)

# get the prices 15 candles in the futures. Why "10"? Not sure, seems like as good a number as any. :-)
# but it does kind of fit into the most dense part of the scatterplot
data$tradeopenprice <- shift(data$open, 1)
data$tradecloseprice <- shift(data$close, 10)
```

```{r}
trades <- subset(data, data$row %in% tmp2$row)

# set the direction for the trades
trades$direction <- 1
trades$direction <- ifelse(trades$minmax == 1, -1, trades$direction)
```

```{r}
# set cost to 0 for now, and as before, calculate the profit/loss per trade, and the running balance
trades$cost <- 0.000
trades$profit <- trades$direction*(trades$tradecloseprice - trades$tradeopenprice) - trades$cost
trades$balance <- cumsum(trades$profit)


# ------------------- plot the results
plot(trades$balance)
# -------------------
```

```{r}
# set the trade cost
trades$cost <- 0.0002
trades$profit <- trades$direction*(trades$tradecloseprice - trades$tradeopenprice) - trades$cost
trades$balance <- cumsum(trades$profit)

# ------------------- plot the results
plot(trades$balance)
# -------------------
```

